### ISSUE TITLE
does the code work on non-testthat R packages?

### ISSUE THREAD

**Issue by tdhock** [analyticalmonk/Rperform#10]
can you please post results of https://github.com/HenrikBengtsson/matrixStats/tree/master/tests ?

**Comment by tdhock** [comment]
if you get this working it may be nice to write it up in a blog post.

**Comment by da-ta-vinci21** [comment]
The memory functionality is working fine for the matrixStats package. For example,
```
> Rperform::plot_mem(test_path = "./tests/benchmark.R", num_commits = 5)
```
![matrixstats_benchmarkmem](https://cloud.githubusercontent.com/assets/4419448/8873126/1a1a1158-3221-11e5-9b8d-32a242c3bc9e.jpeg)


But there is an issue with the time functionality.
When I run it on any test on the package for the first time in the session, it works fine. For example,
```
> Rperform::plot_time(test_path = "./tests/rowWeightedVars.R", num_commits = 5)
```
![matrixstats_timeweightedvvars](https://cloud.githubusercontent.com/assets/4419448/8873162/72ebfed6-3221-11e5-9cb3-d451d327b4ce.jpeg)

But after that it gives the following error message irrespective of the fact whether I run the function again on the same test file or another file.

```
> Rperform::plot_time(test_path = "./tests/rowWeightedVars.R", num_commits = 5)

Error in .Call("loop_apply", as.integer(n), f, env) : 
  "loop_apply" not resolved from current namespace (plyr)
```

```
> Rperform::plot_time(test_path = "./tests/allocMatrix.R", num_commits = 5)

Error in .Call("loop_apply", as.integer(n), f, env) : 
  "loop_apply" not resolved from current namespace (plyr)
```

If I restart the R session, it works fine again for the first time and then the same problem occurs. I am looking into the cause for this right now.

**Comment by analyticalmonk** [comment]
It seems to be working on this particular package.
For example,

```
Rperform::plot_time(test_path = "./tests/rowWeightedVars.R", num_commits = 5)
```

![matrixstats_timeweightedvvars](https://cloud.githubusercontent.com/assets/4419448/8873766/8ee5730a-3227-11e5-9ede-56fa9ed87451.jpeg)

```
Rperform::plot_mem(test_path = "./tests/benchmark.R", num_commits = 5)
```

![matrixstats_benchmarkmem](https://cloud.githubusercontent.com/assets/4419448/8873773/9eae163e-3227-11e5-960f-81044b0f2af9.jpeg)

Is there any other package that you know of which doesn't use testthat?

**Comment by tdhock** [comment]
great to see that your code also works for packages that do not use testthat!

I guess in practice when people want to run your code on travis you should provide some function like `performance_test_all_files` that can be run via

``` r
performance_test_all_files("matrixStats/tests")
```

for packages that do not use testthat, and 

``` r
performance_test_all_files("stringr/tests/testthat")
```

for packages that do use testthat. In both cases maybe you need some more arguments to determine which branches to test (defaults for these arguments you can hopefully determine automatically on travis via the pull request environment variables).

there are many packages that don't use testthat! here are some of my packages which don't use testthat:

https://github.com/tdhock/plotMakefile

https://github.com/tdhock/rankSVMcompare

https://github.com/tdhock/ggplotly

https://github.com/tdhock/revector

https://github.com/tdhock/directlabels

https://github.com/tdhock/inlinedocs

**Comment by analyticalmonk** [comment]
I tested the ggplotly package using the `plot_html()` function (https://github.com/da-ta-vinci21/Rperform/blob/master/R/plot_metrics.R#L179).

```
Rperform::plot_webpage(test_directory = "./tests")
```

The resulting webpage: http://da-ta-vinci21.github.io/Rperform_ggplotly/

**Comment by tdhock** [comment]
that looks reasonable Akash. Good job!

I would suggest to delete the `aes(color=test_name)`. since there is only one color, there is no need for a legend. instead please put `ggtitle(test_name)`.

**Comment by analyticalmonk** [comment]
Sure, I will do that.

**Comment by tdhock** [comment]
looks like it works fine on non-testthat packages, good job!
