### ISSUE TITLE
copy some ideas from asv

### ISSUE THREAD

**Issue by tdhock** [analyticalmonk/Rperform#13]
asv is a python library that tries to solve the same problem as Rperform. Maybe the front-end graphics or JSON storage mechanism could be copied?

https://github.com/spacetelescope/asv

**Comment by analyticalmonk** [comment]
@tdhock Was reading up on profiling tools when came across this package: [profvis](https://github.com/rstudio/profvis). A somewhat interesting tool. Have you seen or used it previously?

**Comment by tdhock** [comment]
nope, but maybe email the author to see if he could co-mentor?

**Comment by analyticalmonk** [comment]
Closing this for now.
Will open individual issues for any feature that we might copy, similar to #18.
