### ISSUE TITLE
examples?

### ISSUE THREAD

**Issue by tdhock** [analyticalmonk/Rperform#3]
Can you please post some examples about how to use the code that you have developed so far?

Usually I post some code examples in a README.org (or README.md) file in the root directory of each of my github repositories. For example https://github.com/tdhock/PeakSegJoint/blob/master/README.org has installation and example instructions. I would recommend you do the same for your project.

Also you should write brief examples in the Rd files for each of your package's functions, see https://support.rstudio.com/hc/en-us/articles/200532317-Writing-Package-Documentation for more details.

**Comment by analyticalmonk** [comment]
I have added a README for the project as well as the initial documentation for the package.
