### ISSUE TITLE
editable wiki?

### ISSUE THREAD

**Issue by tdhock** [analyticalmonk/Rperform#32]
Hey @analyticalmonk I wanted to post a question on https://github.com/analyticalmonk/Rperform/wiki/Integrating-Rperform-with-Travis-CI but the wiki is not editable. can you make it editable?

I was trying to follow your instructions and get Rperform working with https://github.com/tdhock/coseg and I was not sure what permissions I need to give to the access token. repo?

**Comment by analyticalmonk** [comment]
Hey @tdhock made it editable. However, the instructions on that page aren't valid anymore. I will be editing that some time tomorrow.

Created a [dummy package](https://github.com/analyticalmonk/RperformTestPackage) and working on creating some tests for Rperform right now. Also, here's a (in-progress) tutorial about using Rperform: [Tutorial: Using Rperform with packages](https://github.com/analyticalmonk/Rperform/wiki/Tutorial:-Using-Rperform-with-packages). It uses the dummy package to help someone new to Rperform get up to speed.

**Comment by analyticalmonk** [comment]
In addition to updating the wiki, I would be creating a brief hands-on tutorial about using Rperform on  Travis. That should clear things up.

**Comment by analyticalmonk** [comment]
@tdhock About the access token, _repo_ would do. In fact, since it's a public repo, just the _public_repo_ option (under _repo_) would do as well.

I will be updating the wiki but here's the quick setup guide (from my email last week):

> In a nutshell, a repo maintainer would have to complete the following steps to run Rperform with the Travis-CI builds:
> - Create a gh-pages branch and create an 'Rperform' directory on the branch. The html pages produced and containing the test results will be stored here and visible at the link: username.github.io/projectname/Rperform
> - Make appropriate changes to the .travis.yml. This includes creating the required environment variables and sourcing the script in the before_install section as is done in the sample_travis.yml file.

Here's the [sample_travis.yml](https://github.com/analyticalmonk/Rperform/blob/master/SampleFiles_TravisPR/sample_travis.yml) file mentioned in the second point.

**Comment by analyticalmonk** [comment]
@tdhock Here's a new tutorial for integrating Rperform with Travis CI builds: [Tutorial: Using Rperform with Travis CI](https://github.com/analyticalmonk/Rperform/wiki/Tutorial:-Using-Rperform-with-Travis-CI)

Also closing this issue since wiki is now editable.
