### ISSUE TITLE
reproducing rperform_test memory leak example?

### ISSUE THREAD

**Issue by tdhock** [analyticalmonk/Rperform#43]
Hi @analyticalmonk my student @LooDaHu is trying to reproduce the example on the README where you show that the rperform_test branch has a memory leak after 5 commits... where did you get that repo/branch? I don't see any branch named rperform_test in the stringr repo.
Thanks

**Comment by tdhock** [comment]
hi @analyticalmonk can you please look up where the test package (with memory leak on commit 5) can be found? https://github.com/analyticalmonk/Rperform/wiki/Obtaining-package-performance-data-using-Rperform#examples-1

**Comment by analyticalmonk** [comment]
Hi @tdhock, there's no test package per se. As the wiki mentions, I'd modified a test ([test-dup.r](https://github.com/tidyverse/stringr/blob/master/tests/testthat/test-dup.r)) from the stringr package for the purpose of creating a demo.
The actual `stringr` package didn't have a leak. I'd forked the repo, created a new branch (`rperform_test`), put in code in the aforementioned test that would mimic a leak and then run Rperform across this new branch and master. That can easily be replicated.

Does that answer your query?

**Comment by tdhock** [comment]
yes that helps, thanks. so if I understand correctly you did that manually? 

there is no code that does that for you automatically? I mean, code that clones stringr and then adds 5 commits, and then runs Rperform?

**Comment by analyticalmonk** [comment]
@tdhock You're right. There's no script; I'd done that manually.

**Comment by tdhock** [comment]
ok. one last question. is that repo (where you cloned and the did those 5 commits) online somewhere, one of your github repos?

**Comment by analyticalmonk** [comment]
Sadly, no.
Looks like I hadn't pushed it since its not present in my [stringr fork](https://github.com/analyticalmonk/stringr ).

**Comment by tdhock** [comment]
ok thanks for the info
