### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by analyticalmonk** [analyticalmonk/Rperform#48]
- [ ] **Fix example code**: If one tries to follow the `Basic Examples` section provided in the README, they will encounter errors. These happen due to wrong test paths for package 'stringr' being specified in the Rperform code snippets. We need to update the code so that a new user can easily get started with using Rperform.
- [ ] **Replace Travis build badge with Github workflow badge**

**Comment by EngineerDanny** [comment]
I am not quite sure though if the  Github Workflow **R CMD Check** should be placed in the **README.md** instead of the Travis CI Build.
What are your suggestions on this @analyticalmonk ?

**Comment by analyticalmonk** [comment]
> I am not quite sure though if the Github Workflow R CMD Check should be placed in the README.md instead of the Travis CI Build

@EngineerDanny Sorry but I did not understand your question. Why are you considering placing the Github workflow piece in the README?

**Comment by EngineerDanny** [comment]
The result badge could be there to show the users whether the R CMD Check test is passing or failing.
It is required that R CMD Check must pass before a package can be published.

**Comment by EngineerDanny** [comment]
For instance [binsegRcpp](https://github.com/tdhock/binsegRcpp), [stringr](https://github.com/tidyverse/stringr) all have the R CMD Check result badge. Hope you understand my point @analyticalmonk

**Comment by analyticalmonk** [comment]
@EngineerDanny Yes, we should add the appropriate badge. I have also updated the issue to reflect that as a task.

**Comment by EngineerDanny** [comment]
Great
