### ISSUE TITLE
standardize time and memory profiling functions

### ISSUE THREAD

**Issue by tdhock** [analyticalmonk/Rperform#7]
Can you please standardize the function names so that they are consistent between time and memory profiling? For example change get_times to time_compare, to be consistent with mem_compare?

Also for data viz with ggplot2 it would be best if these functions return data frames that can be easily combined with rbind.

For example both could return data frames with columns test_path, test_name, status, msg_val, date_time, metric_name, metric_value. metric_name would be one of seconds, swap_mb, leak_mb, and metric_value would be a numeric variable.

**Comment by analyticalmonk** [comment]
I have incorporated the suggested changes. Check out the updated README file.

**Comment by tdhock** [comment]
great!
